## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 0.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt: # apt-get for linux
    packages:
    - libglpk-dev

before_script: # homebrew for mac
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install homebrew/science/glpk; fi

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TransitmapSolver")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
